### ISSUE TITLE
Realizar a primeira reunião com o cliente

### ISSUE THREAD

**Issue by ifac0** [IF977/Checkroom#1]
- Reunião realizada dia 07/04 para esclarecer dúvidas sobre o processo atual do tema do projeto.

**Comment by nik0llas** [comment]
Áudio referente à primeira entrevista realizada no dia 07/04 com a cliente.
Pontos discutidos:
- Problemas atuais: Que são enfrentados pelos professores e alunos hoje em dia.
- Solução: O nosso projeto será a solução justamente de alguns desses problemas abordados.

[Audio_entrevista1.zip](https://github.com/IF977/Checkroom/files/215695/Audio_entrevista1.zip)

**Comment by ifac0** [comment]
Ata da primeira reunião com o cliente, mais detalhes no documento.
Data: 07/04

[Arquivo](https://github.com/IF977/Checkroom/files/215719/Ata.da.reuniao.08-04.docx)

**Comment by mpocin** [comment]
O arquivo deve estar em uma pasta no proprio projeto
