### ISSUE TITLE
Gerar Gráfico

### ISSUE THREAD

**Issue by ifac0** [IF977/Checkroom#11]
Como **Usuário do Sistema** (Aluno, Professor, Coordenador)
Eu quero **gerar gráficos** durante a realização da disciplina 
Para ter melhor **visualização dos dados**.

**Comment by mpocin** [comment]
não entendi o sobre o decorrer da disciplina. seria durante a realização da disciplina?

**Comment by nik0llas** [comment]
Isso Marcela! Durante a realização da disciplina, os usuários poderão visualizar gráficos de por exemplo, a partir de que mês os alunos começaram a falta certa disciplina.. Deu pra entender? @mpocin

**Comment by mpocin** [comment]
perfeito... então vai mudar p durante a realização da disciplina? acho q do
outro jeito n fica tão explícito, por isso perguntei.

2016-04-18 18:38 GMT-03:00 nik0llas <notifications@github.com>:

> Isso Marcela! Durante a realização da disciplina, os usuários poderão
> visualizar gráficos de por exemplo, a partir de que mês os alunos começaram
> a falta certa disciplina.. Deu pra entender? @mpocin
> <https://github.com/mpocin>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/IF977/Checkroom/issues/11#issuecomment-211593897>
>



-- 
CIn - Centro de Informática - UFPE
"Be Like Water" - Lao Tzu

**Comment by nik0llas** [comment]
Isso! Acabei de corrigir pra ficar mais explícito.

**Comment by mpocin** [comment]
Meninos, outra coisa, usuários do sistema seria professor, coordenador, e/ou aluno, se sim, especifiquem, ao invés de colocar usuário do sistema

**Comment by nik0llas** [comment]
Corrigido. @mpocin
