### ISSUE TITLE
Adicionar Professor

### ISSUE THREAD

**Issue by ifac0** [IF977/Checkroom#13]
Como **Cliente** (Coordenador) 
Eu quero adicionar **professores** 
Para que os **professores** tenham acesso as **funcionalidades**.

**Comment by mpocin** [comment]
quem acessa as funcionalidades: coordenador ou professor?

**Comment by ifac0** [comment]
As funcionalidades do professor, A coordenação é o nosso cliente, e ele é responsável por adicionar os professores no sistema para assim poder criar as turmas e os alunos poder confirmar presença.

**Comment by mpocin** [comment]
poderia entao ser, para que eles tenha acesso as funcionalidades do sistema

**Comment by caiovfreitas** [comment]
@mpocin issue #13 corrigida

**Comment by nik0llas** [comment]
Pronto, corrigido! @mpocin

**Comment by mpocin** [comment]
Meninos, outra coisa... retirem a palavra sistema, passei despercebido, mas ela n precisa ser citada, já q se trata do sistema.

**Comment by nik0llas** [comment]
Corrigido. @mpocin

**Comment by nik0llas** [comment]
essa issue não foi aceita? @mpocin

**Comment by mpocin** [comment]
Agora foi... kkkkk
