### ISSUE TITLE
Descrição das HU

### ISSUE THREAD

**Issue by ifac0** [IF977/Checkroom#16]
@mpocin

**Comment by mpocin** [comment]
Análise das histórias dos usuários:
#5 OK
#6 OK
#7 OK
#8 OK
#9 Pending
#10 OK
#11 Pending
#12 OK
#13 Pending
#14 OK
#15 OK

**Comment by nik0llas** [comment]
Issues #9 #11 #13 corrigidas! 
Esperando o feedback. @mpocin

**Comment by mpocin** [comment]
Issue #13 ainda falta deixar explicito que o professor terah acesso ao sistema.

**Comment by caiovfreitas** [comment]
Issue #13 Corrigida
@mpocin

**Comment by mpocin** [comment]
Pronto meninos! Historias dos usuarios fechada!
