### ISSUE TITLE
Criar Mockups

### ISSUE THREAD

**Issue by nik0llas** [IF977/Checkroom#19]
Criar os mockups referentes as HUs de **logar no sistema** tanto pelo navegador web como mobile, 
Criar os mockups referentes ao **perfil** do coordenador, professor e aluno. E também da tela de Gerar **QRCode** e a de **Leitura do QRCode**.

**Comment by ifac0** [comment]
Mockups na pasta Docs

**Comment by ifac0** [comment]
@mpocin , precisa fazer os storyboards Lo-Fi ???

**Comment by mpocin** [comment]
precisa sim @ifac0, tah lah nas entregas. pode fazer de 3, de preferencia, as principais.
Outra coisa, coloquem uma **pequena descricao na tarefa**... ou mudem o titulo para  **criar mockup de tal tela**. Lembre-se que uma issue, em geral, eh uma tarefa a ser executada, sendo assim mockups n diz nada do q irah ser realizado. e uma tarefa, eh uma acao atomica, sendo em geral atribuida a uma acao apenas.
Adquiram essa pratica para todas as issues que voces forem criar a partir de agora, coloquem a **label** especifica e tb o **milestone** referente. assim vcs podem depois referenciar o commit - https://github.com/IF977/Checkroom/pull/4/commits/a74677d643aab1db19906a030011b4055b8fc7eb onde a informacao foi adicionada
Outra dica eh que quando forem realizar um commit que fecha determinada tarefa vcs coloquem a expressao **closes #x** na msg de commit (exemplo: closes #19, onde x eh o numero da tarefa a ser fechada). assim qndo fizar o merge c a master a tarefa fecha automaticamente.

**Comment by nik0llas** [comment]
@mpocin Marcela, a equipe não conseguiu entender muito bem.
Vê só, a gente tem que criar uma issue para cada Mockup e contendo uma pequena descrição de cada tela né isso? E outra dúvida, essas issues sobre mockups qual a label certa? Seria feature ou docs?

**Comment by ifac0** [comment]
closes #19

**Comment by nik0llas** [comment]
@mpocin editei o nome da issue, porque achei assim mais adequado, concorda?

**Comment by ifac0** [comment]
closes #19

**Comment by mpocin** [comment]
Oie meninos, eh isso mesmo. Mas cmo vcs jah commitaram os mockups nao precisam abrir novas issues para isso. Facam isso somente para os storyboards e novas issues que irao ser abertas, por exemplo: **Criar storyboard de Login do Usuario**. No caso dos mockups e storyboards adicionem a label **docs**.
A mensagem de closes vcs soh usam quando foram dar commit no git. 
exemplo: `git commit -m 'adiciona mockup referente a tela de ajuda - closes #19'`

**Comment by nik0llas** [comment]
@mpocin Descrição da issue feita!

**Comment by mpocin** [comment]
Analise dos mockups:
**Acesso aluno**: Deveria ter logo do app acima do form de login? Falta botao cancelar; Falta botao de ajuda.
**Home aluno**: Seria a tela inicial do aluno? Teria que ter o minimo de informacao, como nome e curso? O que significa aquele v de correto? Falta botao de cancelar? A seta para acessar deveria ser a direita.
**Leitor**: Falta botao de cancelar; Se tiver botao de cancelar nao precisa de seta no confirmar; As setas confundem quanto a que direcionamento a tela vai dar.
**Pagina inicial web**: Deveria ter pelo menos uma informacao sobre a que se proproe a aplicacao; botao de ajuda; setas deixam a aplicacao nao intuitiva;
**Perfil aluno**: Falta logo da aplicacao; O quadro irah mostrar todas as disciplinas matriculadas ou terah uma inicial como padrao? Caso tenha, seria necessario alguma opcao de configuracao do perfil do aluno. Total de faltas nao deveria aparecer somente quando escolher a disciplina? ao inves de presencas nao seria interessante outro nome para o quadro? jah q ela mostra tanto presenca quanto ausencia, talvez status da frequencia ou frequencia.
**Perfil coordenacao**: O coordenador n terah foto? Falta logo da aplicacao; Botao de cancelar ao cadastrar professor; Grafico soh eh visivel apos escolha da disciplina? Quais as informacoes contidas no grafico
**Perfil professor**: Codigo se refere a que? Falta logo da aplicacao; botao cancelar tanto em cadastrar aluno quanto confirmar presenca;
**Perfil**: Falta logo da aplicacao; Setas nao estao intuitivas; O que seria nova leitura? ao inves de presencas, frequencia? Soh o aluno acessa a aplicacao via mobile?
**QRCode - professor**: Falta logo da aplicacao; Ao inves de alunos, frequencia? As informacoes sobre a disciplina nao ficariam melhor no lado esquerdo da tela? Botao de sair;

**Comment by mpocin** [comment]
Renomeiem as figuras para indicar o que seria web e o que seria app, por exemplo: **web-perfil-professor**; **app-perfil-aluno** ou outro jeito que fique melhor para identificar de qual tipo de aplicacao se trata.
Organizem as atas em uma pasta, e se possivel tb mudem a nomeclatura para que fique mais facil localizar por data. O postmostem tb deve estar em uma pasta separada.

**Comment by ifac0** [comment]
Tudo atualizado, qualquer duvida é só perguntar. E o repositorio já se encontra organizado.

**Comment by mpocin** [comment]
Meninos, mais algumas correcoes:
A seta para confirmar, sair, etc vai ficar assim **<** mesmo? P mim eh um tanto estranho ter algo  de confirmar ou qualquer outra acao q o botao indica < a nao ser voltar.
a tela **app-leitor-aluno** ainda tah faltando o log da app. poderia ficar igual a do app-perfil-aluno.
em **app-perfil-aluno**, n seria status de frequencia ao inves de presencas? assim mantem o mesmo nome tanto na web qnto no app. ainda n entendi o botao nova leitura.
em **web-perfil-coordenacao** o bloco de cadastro do professor poderia ficar alinhado com o bloco dos dados da disciplina
em **web-qrcode-professor** p bloco das informacoes poderia vim um pouco mais a direita, acompanhando o alinhamento da tabela abaixo e o bloco do qrcode poderia ir tb um pouco para direita. falta botao sair.
**coordenacao** nao terah foto?

**Comment by ifac0** [comment]
@mpocin , não são setas, e sim o botão que o bolsamiq oferece para versão mobile. As demais alterações já foram feitas. E não, por que coordenação pode mudar, ai preferimos deixar sem foto mesmo

**Comment by mpocin** [comment]
certinho... esse botao do balsamiq eh mto tosco. acho q nao tem mais nada p ser mudado.
sugiro que vcs revisem tdo q foi modificado e verifiquem se, para vcs, falta algo. nao havendo, pode realizar o merge e colocar a tag. e depois fechar as issues referentes a sprint0 caso as mesmas nao sejam concluidas automaticamente.
obrigada pelas correcoes!
no mais, mto bom o trabalho de vcs. notas na planilha em breve.
vcs tao de parabens!

**Comment by ifac0** [comment]
@mpocin  fiz o merge para master e fiz a tag, porém não ta aparecendo a tag.

**Comment by nik0llas** [comment]
@mpocin brigado pelas correções e pela atenção que tas dando à nossa equipe Marcela.
Quando realizamos o merge os pull requests fecharam automaticamente, só que a tag não apareceu e as issues também não fecharam automaticamente, no caso vou fechar manualmente, ai queria saber se são todas as 13 issues que estão abertas.

**Comment by nik0llas** [comment]
@mpocin acredito que é só pra fechar as issues dos Mockups e Storyboards mesmo, deixei as issues referente as HUs abertas.

**Comment by mpocin** [comment]
isso mesmo, elas serao implementadas nas outras sprints, por isso podem ficar abertas. de acordo com a implementacao, vcs fazem a relacao com o milestone.
soh lembrem de abrir novas issues, qndo necessario, naquele mesmo padrao dito nos comentarios.
@ifac0 vc criou a tag aqui ou pela linha de comando? caso tenha criado pela linha de comando precisa executar esse comando:
`git push origin master --tags`
para fechar as issues, precisa daquele comando nesse comentario https://github.com/IF977/Checkroom/issues/19#issuecomment-213865385

**Comment by mpocin** [comment]
Meninos, a tag ainda não foi colocada no repositório. Ah, também é necessário que vcs fechem o milestone referente a sprint0.
^^

**Comment by nik0llas** [comment]
@mpocin Acabei de fechar a Milestone, e foi criada a tag referente a Sprint0. Agora ta tudo ok?

**Comment by mpocin** [comment]
perfeito! ^^
