### ISSUE TITLE
Segunda Reunião com o Cliente

### ISSUE THREAD

**Issue by ifac0** [IF977/Checkroom#2]
Reunião realizada dia 12/04/2016.

- Gravação do video

**Comment by nik0llas** [comment]
Membros participantes:
- Caio Freitas
- Francisco Gomes
- Ivan Felipe
- Nikollas Filgueiras

Segue o link do vídeo da entrevista com o cliente:
https://youtu.be/jtpueaPMXig

**Comment by mpocin** [comment]
O link deve estar junto ao doc da reuniao.
