### ISSUE TITLE
Criar Storyboards

### ISSUE THREAD

**Issue by ifac0** [IF977/Checkroom#20]
Criar as storyboards referentes as HUs de logar no sistema, gerar relatórios para a coordenação e criação de QRCode do professor.

**Comment by ifac0** [comment]
@mpocin , algo que devemos corrigir?

**Comment by ifac0** [comment]
close #20

**Comment by mpocin** [comment]
Pronto, soh faltou a descricao da tarefa, como por exemplo: **Criar as storyboards referentes as HUs de logar no sistema e blablabla**. A parte do commit ficou perfeita, cmo vcs viram, ele aparece aqui na issue.
Amanha dou o feedback sobre os mockups e storyboards.
Lembrar q a issue soh eh concluida ou fechada apos o merge c a master ou caso seja realmente necessaria a sua conclusao.

**Comment by nik0llas** [comment]
@mpocin Tá certo Marcela, iremos completar isso e avisamos! Já editei os nomes das duas issues pro infinitivo. Sobre o postmortem, se possível também dá um feedback pra gente :))

**Comment by mpocin** [comment]
Gente, uma duvida: professor cadastrar aluno n eh um pouco estranho? visto que a lista de alunos eh fornecida pelo SIG@ e acredito que o mesmo nao consegue fazer isso nem mesmo no SIG@, somente coordenacao. Mas as storyboards ficaram boas.
Outra duvida, o QRCode ficaria disponibilizado onde? via projecao? precisa lembrar que nem todas as salas do campus dispoe de projetor.

**Comment by caiovfreitas** [comment]
**Sobre a disponibilização do QRCode:** A Princípio pensamos em usar uma projeção, mas além deste problema, também poderia ocorrer do professor ter que parar a aula a todo instante, para que o aluno que chegar no meio da aula marcar presença. Daí surgiu uma ideia de ser impresso, onde o professor colocaria o QRCode impresso, e os alunos teriam o trabalho só de ir no papel impresso e escanear, porém, pode ocorrer uma falha, onde um aluno pudesse tirar uma foto, e enviar pros amigos que não estivessem presentes naquela aula, com isso, pensamos numa solução, que seria fazer com que o aluno só pudesse marcar a presença, com o GPS ligado, daí poderíamos saber de onde o aluno fez o Check-in, e saber se ele esteve realmente em sala ou não.

**Comment by nik0llas** [comment]
Descrição da tarefa feita @mpocin

**Comment by mpocin** [comment]
Certinho meninos, ainda pode ter a falha quanto ao GPS, visto que pode ter interferencia quanto a localizacao.

**Comment by ifac0** [comment]
Entendemos, porém a ideia mais segura ainda é a implantação de um fechadura digital e leitura do cartão com RFid na entrar e saída da aula. Já que o projeto não vai ser tão abrangente estamos tentando focar na utilização do QRCode, e quando estudarmos melhor a tecnologia veremos outros métodos de garantir a segurança.

**Comment by mpocin** [comment]
Certinho, foi soh p tirar duvida mesmo.

**Comment by ifac0** [comment]
Tudo bem, obrigado pela ajuda.

**Comment by nik0llas** [comment]
closes #20

**Comment by nik0llas** [comment]
close #20
