### ISSUE TITLE
Fazer Login com Api do Google

### ISSUE THREAD

**Issue by nik0llas** [IF977/Checkroom#29]
Como **Usuário do Serviço**
Eu quero fazer o acesso com a **API do Google.**
Para ter um acesso mais ágil

**Comment by mpocin** [comment]
defina prático? seria sem a necessidade de me cadastrar no sistema ou seria a vantagem de integrar c serviços do google?

**Comment by ifac0** [comment]
@mpocin vai ser prático de ambos pontos de vista, por conta que iria facilitar o acesso de todos os usuários. mas deixamos essa issue para o final, por que estamos focando agora em desenvolver a base do projeto para depois ver como otimizar

**Comment by nik0llas** [comment]
@mpocin Marcela, mudei para: "Para ter um acesso mais ágil" fica melhor?

**Comment by mpocin** [comment]
nikollas, falei c ivan já e expliquei o porquê da preocupação com o
prático. cmo vcs vão testar ágil qndo converter para o BDD? por isso sugeri
a mudança para algo que palpável, q vcs tenham cmo avaliar no BDD.

-- 
CIn - Centro de Informática - UFPE
"Be Like Water" - Lao Tzu

**Comment by nik0llas** [comment]
@mpocin Ivan me disse que tinha conversado contigo que tinha comunicado sobre a dificuldade na conversão para o BDD, mas não conseguimos pensar em uma palavra que melhor se adeque nessa HU, tu tem alguma sugestão? :)))

**Comment by mpocin** [comment]
eu pensei em facilitar o acesso a aplicação, mas n sei se seria o ideal, pq
nesse caso cmo vcs iriam testar isso? ou poderia ser para não ter
necessidade de me cadastrar na aplicação (isso vcs teriam cmo testar).
pensem em algo melhor ou tentem seguir pelo caminho de que seria algo que
vcs pudessem testar

**Comment by nik0llas** [comment]
@mpocin Tranquilo Marcela, vamos pensar sim, qualquer coisa vamos te encher o saco again, kkkkkkkkkk

**Comment by mpocin** [comment]
sem prob.
pode perguntar sim, a nota da sprint0 foi atualizada.

**Comment by nik0llas** [comment]
@mpocin Vi agora Marcela, tu poderia dizer pra gente o que foi esse meio ponto perdido? Pq quando valia de 0 a 8 a gente tirou 8.. :D
