### ISSUE TITLE
Descrição e Justificativa do Repositório concluida!

### ISSUE THREAD

**Issue by ifac0** [IF977/Checkroom#3]
@mpocin

**Comment by ifac0** [comment]
Corrigido, @mpocin

**Comment by ifac0** [comment]
Corrigido de novo @mpocin

**Comment by mpocin** [comment]
Pessoal, a descrição ficou mto boa. Porém tem alguns erros ortográficos que precisam ser corrigidos. Seguem:
- cada aluno **confirma** (confirmar?)
- Futuramente podendo usar **dessa plantaforma** (a plataforma?) juntamente com uma **fechadura digital** (assinatura digital?) e os cartões do aluno com RFid juntamente com a Caderneta Eletrônica
- propomos uma solução onde **realizaria** (será realizado?) um controle maior
- Tendo no fim um maior controle e **menor perca de tempo** (agilidade?) da (na?) aula para realizar essa atividade.

Talvez ao invés das telas vcs poderiam trocar pelas **funcionalidades** que o sistema irá apresentar, por exemplo: Gerar QRCode, Controlar presença de alunos, Cadastrar alunos manualmente... e por aí vai. Exemplo de um readme com features: https://github.com/lukehoban/es6features

Para o resto da iteração, criem uma **branch** c o nome **sprint0** e vão adicionando as coisas referente a ela. ao final da sprint, abram um **pull request** p que eu possa analisar o que foi adicionado. depois que eu der o feedback, vcs aceitam o pull request e passam a **tag** referente a sprint0.

Isso vai facilitar tanto o acompanhamento por mim quanto por vinícius. Repitam o processo a cada sprint.

Se puderem, criem um team para a equipe, fica melhor p gerenciar os membros.
@ifac0 @nik0llas @caiovfreitas @Fgsj10

**Comment by nik0llas** [comment]
Marcela o único erro de ortografia que tem é "plantaforma". O resto que tu mencionou já está correto, tu só fez trocar algumas palavras por sinônimo e trocar a forma verbal, mas o significado é o mesmo. Não entendi sua colocação ao apontar "erros" que na verdade são inexistente, se der para ser mais clara agradecemos. @mpocin

**Comment by mpocin** [comment]
@nik0llas O tempo verbal estah errado. na primeiro colocacao "podendo assim cada aluno confirma sua presenca" deve-se utilizar a forma infinitva do verbo. eh um tipico caso de utilizacao de gerundio + infinitivo.
na colocacao "propomos uma solucao onde realizaria", o ideal eh utilizar o futuro do presente pq indica uma acao que serah realizada e nao futuro do preterito, pq o mesmo necessita de uma condicao para acontecer.
no caso de "menor perca de tempo", o correto seria utilizar perda, pois o mesmo eh um substantivo, podendo nesse caso ser facilmente trocado por agilidade. perca eh uma forma verbal utilizada no imperativo (que nao eh o caso) ou presente do subjuntivo (que tb nao eh o caso).
espero ter sido clara agora!

**Comment by mpocin** [comment]
@nik0llas complementando (essa fui buscar na net p me certificar de que nao estou passando a informacao errada). fechadura digital refere-se a um dispositivo utilizado em portas ou outros itens que permite fecha-lo e abri-lo de forma automatica, seja atraves de impressao digital, senha, RFid ou outro dispositivo eletronico, como celular ou tokens.
jah o termo assinatura digital eh uma tecnologia utilizada para gerar documentos digitais de forma legal (vide https://pt.wikipedia.org/wiki/Assinatura_digital) e acredito que seria o caso da aplicacao de vcs. caso esteja errada, favor ser mais claro como sera dado a utilizacao da fechadura.
desculpe a demora em responder, mas queria passar a informacao mais acurada possivel.
